# Forward Propogation

## Read Inputs

In [1]:
import numpy as np
X = np.array([[1.0, 0, 1.0, 0], [1.0, 0, 1.0, 1.0], [0, 1.0, 0, 1.0]])
Y = np.array([[1, 1, 0]])
print('Input shape:', X.shape, 'Input:', X)
print('Output shape:', Y.shape, 'Output:', Y)

Input shape: (3, 4) Input: [[1. 0. 1. 0.]
 [1. 0. 1. 1.]
 [0. 1. 0. 1.]]
Output shape: (1, 3) Output: [[1 1 0]]


## Initialize weights & bias

In [2]:
wh = np.random.random((4,3))
#wh = np.array([[0.42, 0.88, 0.55], [0.1, 0.73, 0.68], [0.60, 0.18, 0.47], [0.92, 0.11, 0.52]])
bh = np.random.random((1,3))
#bh = np.array([[0.46, 0.72, 0.08]])
print('layer1 weights shape', wh.shape)
print('layer1 weights', wh)
print('layer1 bias shape', bh.shape)
print('layer1 bias', bh)

layer1 weights shape (4, 3)
layer1 weights [[0.06038098 0.05442538 0.96376134]
 [0.64180367 0.8070637  0.1598953 ]
 [0.49875286 0.3776959  0.25468489]
 [0.92692758 0.67455849 0.00244359]]
layer1 bias shape (1, 3)
layer1 bias [[0.57898632 0.33377876 0.58512972]]


## Calculate hidden layer inputs

In [3]:
z1 = np.add(np.dot(X,wh),bh)
print(z1)

[[1.13812016 0.76590005 1.80357595]
 [2.06504774 1.44045854 1.80601955]
 [2.14771757 1.81540095 0.74746862]]


## Calculate hidden layer activations

In [4]:
def sigmoid(x):
    return 1/(1 + np.exp(-1 * x))
a1 = sigmoid(z1)
print(a1)

[[0.75733433 0.68263333 0.85858368]
 [0.8874593  0.80852565 0.85888011]
 [0.8954553  0.86001336 0.67862687]]


## Calculate output layer inputs

In [5]:
wout = np.random.random((1,3))
#wout = np.array([[0.3, 0.25, 0.23]])
bout = np.random.random((1,1))
#bout = np.array([[0.69]])
z2 = np.add(np.dot(wout,a1),bout)
output = sigmoid(z2)
print(output)

[[0.84757414 0.83217936 0.84747263]]


## Slope of sigmoid

In [6]:
error = Y - output
print('error:', error)
slope_output_layer = output*(1 - output)  #derivative of sigmoid = sigmoid * (1 - sigmoid)
print('slope_output_layer:', slope_output_layer)
slope_hidden_layer = a1 * (1 - a1)
print('slope_hidden_layer', slope_hidden_layer)

error: [[ 0.15242586  0.16782064 -0.84747263]]
slope_output_layer: [[0.12919222 0.13965687 0.12926277]]
slope_hidden_layer [[0.18377904 0.21664507 0.12141775]
 [0.09987529 0.15481192 0.12120507]
 [0.09361511 0.12039038 0.21809244]]


## Delta at output layer

In [7]:
d_output = error * slope_output_layer
print('d_output:', d_output)

d_output: [[ 0.01969223  0.0234373  -0.10954666]]


## Delta at hidden layer

In [8]:
error_hidden_layer = np.dot(np.transpose(d_output), wout)
print('error_hidden_layer:',error_hidden_layer)

error_hidden_layer: [[ 0.01243344  0.015063    0.00389182]
 [ 0.01479803  0.01792768  0.00463197]
 [-0.06916644 -0.08379451 -0.02164996]]


In [9]:
d_hiddenlayer = np.multiply(error_hidden_layer, slope_hidden_layer)
print('d_hiddenlayer:',d_hiddenlayer)

d_hiddenlayer: [[ 0.00228501  0.00326332  0.00047254]
 [ 0.00147796  0.00277542  0.00056142]
 [-0.00647502 -0.01008805 -0.00472169]]


## Update weights at hidden & output layers

In [10]:
learning_rate = 0.1
wout = wout + np.dot(a1,np.transpose(d_output)) * learning_rate
wh = wh + np.dot(np.transpose(X), d_hiddenlayer) * learning_rate
print('updated wh:', wh)
print('updated wout:', wout)

updated wh: [[0.06075728 0.05502926 0.96386473]
 [0.64115617 0.8060549  0.15942313]
 [0.49912916 0.37829978 0.25478829]
 [0.92642787 0.67382723 0.00202756]]
updated wout: [[0.62507373 0.75860653 0.19131807]
 [0.62562178 0.75915459 0.19186613]
 [0.62773282 0.76126562 0.19397716]]


In [11]:
bh = bh + np.sum(d_hiddenlayer, axis = 0) * learning_rate
bout = bout + np.sum(d_output, axis = 1) * learning_rate
print('updated bh:', bh)
print('updated bout:', bout)

updated bh: [[0.57871511 0.33337383 0.58476095]]
updated bout: [[0.37507959]]
