## Python basics

#### Sorting using List comprehensions

In [2]:
def quicksort(arr):
    if len(arr) <= 1:
        return arr
    eip = arr[len(arr) // 2]
    eip_in = [mlblr_in for mlblr_in in arr if mlblr_in < eip]
    eip_list = [mlblr_in for mlblr_in in arr if mlblr_in == eip]
    eip_dict = [mlblr_in for mlblr_in in arr if mlblr_in > eip]    
    return quicksort(eip_in) + eip_list + quicksort(eip_dict)

print(quicksort([3,6,8,10,1,2,1]))

[1, 1, 2, 3, 6, 8, 10]


### Basic data types

#### Integers & Floats

In [3]:
eip =3 
print(type(eip))
print(eip)
print(eip + 1)
print(eip - 1)
print(eip * 2)
print(eip ** 2)
eip += 2
print(eip)
mlblr = 2.5
print(type(mlblr))
print(mlblr, mlblr + 1, mlblr * 2, mlblr **2)

<class 'int'>
3
4
2
6
9
5
<class 'float'>
2.5 3.5 5.0 6.25


#### Booleans

In [4]:
eip = True
mlblr = False
print(type(eip))
print(eip and mlblr)
print(eip or mlblr)
print(not mlblr)
print(eip != mlblr)

<class 'bool'>
False
True
True
True


#### Strings

In [5]:
eip = "hello"
print(eip.capitalize())
print(eip.upper())
print(eip.rjust(7))
print(eip.center(7))
print(eip.replace('l', '(ell)'))
print(' world '.strip())

Hello
HELLO
  hello
 hello 
he(ell)(ell)o
world


### Containers

#### Lists
[more on lists ](https://docs.python.org/3.5/tutorial/datastructures.html#more-on-lists)

In [6]:
eip = [3, 1, 2]
print(eip, eip[2])
print(eip[-1])
eip[2] = 'foo'
print(eip)
eip.append('bar')
print(eip)
mlblr = eip.pop()
print(mlblr, eip)

[3, 1, 2] 2
2
[3, 1, 'foo']
[3, 1, 'foo', 'bar']
bar [3, 1, 'foo']


#### Slicing

In [7]:
eip = list(range(5))
print(eip)
print(eip[2:4])
print(eip[2:])
print(eip[:4])
print(eip[:])
print(eip[:-1])
eip[2:4] = [8,9]
print(eip)

[0, 1, 2, 3, 4]
[2, 3]
[2, 3, 4]
[0, 1, 2, 3]
[0, 1, 2, 3, 4]
[0, 1, 2, 3]
[0, 1, 8, 9, 4]


#### Loop over lists

In [9]:
# looping over list
mlblr = ['cat', 'dog', 'monkey']
for eip in mlblr:
    print(eip)

cat
dog
monkey


In [11]:
#enumerate over list
mlblr = ['cat', 'dog', 'monkey']
for eip, eip_in in enumerate(mlblr):
    print('#%d: %s' % (eip, eip_in))

#0: cat
#1: dog
#2: monkey


#### List comprehension

In [14]:
eip = range(5)
mlblr = [mlblr_in **2 for mlblr_in in eip]
mlblr_out = [mlblr_in **2 for mlblr_in in eip if mlblr_in % 2 == 0]
print(mlblr, mlblr_out)

[0, 1, 4, 9, 16] [0, 4, 16]


#### Dictionaries
[more on dictionaries](https://docs.python.org/3.5/library/stdtypes.html#dict)

In [32]:
eip = {'cat': 'cute', 'dog': 'furry'}
print(eip['cat'])
print('cat' in eip)
eip['fish'] = 'wet'
print(eip['fish'])
print(eip.get('monkey','N/A'))
print(eip.get('fish','N/A'))
del eip['fish']
print(eip.get('fish','N/A'))

cute
True
wet
N/A
wet
N/A


#### loop over dictionaries

In [19]:
eip = {'cat': 'cute', 'dog': 'furry'}
for mlblr in eip:
    mlblr_out = eip[mlblr]
    print('Key %s => value %s' % (mlblr, mlblr_out))

Key cat => value cute
Key dog => value furry


In [26]:
eip = {'cat': 'cute', 'dog': 'furry'}
for mlblr, mlblr_out in eip.items():
    print('index#%s => value %s' % (mlblr, mlblr_out))

index#cat => value cute
index#dog => value furry


#### Dictionary comprehension

In [22]:
eip = range(5)
mlblr = {mlblr_in: mlblr_in **2 for mlblr_in in eip if mlblr_in %2 == 0}
print(mlblr)

{0: 0, 2: 4, 4: 16}


#### Sets

In [23]:
eip = {'cat','dog'}
print('cat' in eip)
print('fish' in eip)
eip.add('fish')
print('fish' in eip)
print(len(eip))
eip.add('cat')
print(len(eip))
eip.remove('cat')
print(len(eip))

True
False
True
3
3
2


#### loop over sets

In [27]:
eip = {'cat','dog', 'fish'}
for eip_in, eip_out in enumerate(eip):
    print('#%d => value %s' % (eip_in, eip_out))

#0 => value cat
#1 => value fish
#2 => value dog


#### Set comprehensions

In [29]:
from math import sqrt
eip = {int(sqrt(eip_in)) for eip_in in range(30)}
print(eip)

{0, 1, 2, 3, 4, 5}


#### Tuples

In [35]:
eip = {(eip_in, eip_in + 1): eip_in for eip_in in range(10)}
eip_out = (5, 6)
print(type(eip_out))
print(eip)
print(eip[eip_out])
print(eip[1, 2])

<class 'tuple'>
{(0, 1): 0, (1, 2): 1, (2, 3): 2, (3, 4): 3, (4, 5): 4, (5, 6): 5, (6, 7): 6, (7, 8): 7, (8, 9): 8, (9, 10): 9}
5
1


#### Functions

In [36]:
def eip(eip_in, mlblr_in=1):
    if mlblr_in == 1:
        print('Morning %s' % eip_in.upper())
    else:
        print('Afternoon %s' % eip_in)
eip('maglev')
eip('maglev',3)

Morning MAGLEV
Afternoon maglev


#### Classes

In [40]:
class eip_list():
    
    #Constructor
    def __init__(self, eip):
        self.eip = eip
        
    #Instance method
    def mlblr(self, mlblr_out=False):
        if mlblr_out:
            print('Morning %s' % self.eip.upper())
        else:
            print('Afternoon %s' % self.eip)

eip_in = eip_list('Fred')
eip_in.mlblr()
eip_in.mlblr(mlblr_out=True)                  

Afternoon Fred
Morning FRED


## Numpy
is the core library for scientific computing in Python providing high-performance multi-dimensional array object and tools for working with these arrays

### Arrays

In [ ]:
import numpy as np

eip = np.array([1, 2, 3])
print(type(eip))
print(eip.shape)
print(eip[0], eip[1], eip[2])
eip[0] = 5
print eip

eip = np.array([1,2,3],[4,5,6])
print(eip.shape)
print(eip[0,0], eip[0,1], )

In [59]:
import numpy as np

eip_list = np.zeros((2,2))
print(eip_list)

eip_list = np.ones((1,2))
print(eip_list)

eip_list = np.full((2,2),7)
print(eip_list)

eip_list = np.eye(2)
print(eip_list)

eip_list = np.random.rand(2,2)
print(eip_list)

eip_list = np.random.random((2,2))
print(eip_list)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.66992833 0.9836099 ]
 [0.7022896  0.35979794]]
[[0.28183056 0.38291168]
 [0.95845895 0.5803167 ]]


#### Array Indexing

In [61]:
import numpy as np
eip = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
eip_in = eip[:2, 1:3]
print(eip[0,1])
eip_in[0,0] = 77
print(eip[0, 1])

2
77


In [62]:
import numpy as np
eip = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
eip_in = eip[1, :]
eip_out = eip[1:2, :]
print(eip_in, eip_in.shape)
print(eip_out, eip_out.shape)


eip_in = eip[:, 1]
eip_out = eip[:, 1:2]
print(eip_in, eip_in.shape)
print(eip_out, eip_out.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)
